Made the download button text uppercase.
YoshithaRathnayake/CALCULATOR-WEBSITE pull request #128
Opened 2022-10-24 18:55 UTC by Abhishekgupta204

Made the download button text uppercase.

2022-10-24 18:56 UTC, Abhishekgupta204 commented
Issue no. #115 resolved.
Please accept my pull request.

2022-10-25 09:53 UTC, YoshithaRathnayake requested changes

2022-10-25 09:53 UTC, YoshithaRathnayake commented on index.html
> +   <center><p class="paragraph">Hi, I am Yoshitha Rathnayake. This is the Calculator App.This app is made by me using the Python Programming Language. You can download it by clicking on the link give
Can you made a new issue for this and do so it will considered as a new commit for you @Abhishekgupta204

2022-10-25 10:08 UTC, YoshithaRathnayake approved these changes
Good Job !
Thank You @Abhishekgupta204

2022-10-25 10:08 UTC, merged