Solved Issue #30
YoshithaRathnayake/CALCULATOR-WEBSITE pull request #40
Opened 2022-10-20 08:30 UTC by DivyanshVinayak23

2022-10-20 11:33 UTC, YoshithaRathnayake requested changes
Please add the center to the image only bcs if you put it to the download btn a chance of another will missed out @DivyanshVinayak23

2022-10-20 11:34 UTC, YoshithaRathnayake requested changes

2022-10-20 11:34 UTC, YoshithaRathnayake commented on index.html
> +</center>
Please add the center to the image only bcs if you put it to the download btn a chance of another will missed out @DivyanshVinayak23

2022-10-20 13:25 UTC, YoshithaRathnayake requested changes
Resolve the conflicts also @DivyanshVinayak23

2022-10-20 16:44 UTC, DivyanshVinayak23 commented
Done I have fixed it

2022-10-21 01:06 UTC, YoshithaRathnayake commented
Resolve the conflicts also @DivyanshVinayak23

2022-10-22 03:21 UTC, YoshithaRathnayake approved these changes
Thank You!
But the resolving part I did that's very very bad @DivyanshVinayak23

2022-10-22 03:21 UTC, merged