Size of the calculator is reduced
YoshithaRathnayake/CALCULATOR-WEBSITE pull request #54
Opened 2022-10-22 18:08 UTC by Abhishekgupta204

2022-10-22 18:13 UTC, Abhishekgupta204 commented
Issue no. #14 resolved.
Please accept my pull request.

2022-10-23 03:48 UTC, YoshithaRathnayake requested changes

2022-10-23 03:48 UTC, YoshithaRathnayake commented on assets/css/styles.css
> +img{
can you pls add this custom css to the class .big-calculator @Abhishekgupta204

2022-10-23 03:58 UTC, YoshithaRathnayake approved these changes
Good Job !
Thank You @Abhishekgupta204

2022-10-23 03:58 UTC, merged