added a hover effect to download button
YoshithaRathnayake/CALCULATOR-WEBSITE pull request #77
Opened 2022-10-23 11:41 UTC by the3plet

Made a hover effect to download button.
Do merge this branch if you like the feature

2022-10-23 15:29 UTC, YoshithaRathnayake requested changes

2022-10-23 15:29 UTC, YoshithaRathnayake commented on assets/css/styles.css
> +  transform: scale(1.1);
Add a new line at the bottom

2022-10-23 15:30 UTC, YoshithaRathnayake commented
Create a new issue for this @the3plet

2022-10-23 15:33 UTC, closed without merging

2022-10-23 19:00 UTC, the3plet commented
@YoshithaRathnayake  can you please remove spam label. 
Purposefully i have n't done any spamming commit in this pr. 
Can you please explain why you have marked it as spam

2022-10-24 02:32 UTC, YoshithaRathnayake commented
I added the spam label bcs you didn't asked me to do this in an issue however I will remove spam label now bcs this is your first time no? @the3plet