Made the Heading Bold
YoshithaRathnayake/CALCULATOR-WEBSITE pull request #88
Opened 2022-10-23 16:59 UTC by Arcturus22

2022-10-23 16:59 UTC, Arcturus22 commented
This Pull Request is regarding Issue #88

2022-10-23 17:01 UTC, YoshithaRathnayake requested changes

2022-10-23 17:01 UTC, YoshithaRathnayake commented on index.html
> +    <title><b>CALCULATOR | YOSHITHA</b></title>
This isn't the one wanted to bold its the main topic "CALCULATOR | YOSHITHA" @Arcturus22

2022-10-23 17:13 UTC, Arcturus22 commented
Please verify @YoshithaRathnayake

2022-10-24 02:34 UTC, YoshithaRathnayake approved these changes
Perfect!
Thank You @Arcturus22

2022-10-24 02:36 UTC, merged

2022-10-24 08:26 UTC, YoshithaRathnayake commented
@all-contributors please add @Arcturus22 for infrastructure, tests and code

2022-10-24 09:07 UTC, Arcturus22 commented
> @all-contributors please add @Arcturus22 for infrastructure, tests and code

Thanks a lot for this honour.😊

2022-10-24 09:08 UTC, Arcturus22 commented
Added a new Design to the README.md

2022-10-24 09:25 UTC, YoshithaRathnayake commented
> > @all-contributors please add @Arcturus22 for infrastructure, tests and code
> 
> @YoshithaRathnayake Thanks a lot for this honour.😊

Pleasure 😊 @Arcturus22

2022-10-24 09:27 UTC, YoshithaRathnayake commented
> Added a new Design to the README.md

Can you make a new issue and put a screenshot of the design @Arcturus22

2022-10-24 10:12 UTC, Arcturus22 commented
> > Added a new Design to the README.md
> 
> Can you make a new issue and put a screenshot of the design @Arcturus22 

No,I did not mean that.
Please ignore that message.

2022-10-24 13:20 UTC, YoshithaRathnayake commented
> > > Added a new Design to the README.md
> > 
> > 
> > Can you make a new issue and put a screenshot of the design @Arcturus22
> 
> No,I did not mean that. Please ignore that message.

Ok I will ignore that @Arcturus22